version: "3.7"

networks:
  ionet:

services:
  backend:
    build:
      context: ./laravel-backend
      dockerfile: Dockerfile
    container_name: IO_backend
    volumes:
      - ./laravel-backend:/var/www/html
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
    networks:
      - ionet

  postgresdb:
    image: postgres:14-alpine
    container_name: IO_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_app
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - ionet

  frontend:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile
    container_name: IO_frontend
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./vue-frontend:/app/vue-frontend
    depends_on:
      - backend
    networks:
      - ionet
