version: "3.7"

networks:
  ionet:

services:
  server:
    image: nginx:stable-alpine
    container_name: IO_nginx
    ports:
      - "8000:80"
    links:
      - backend
    volumes:
      - ./laravel-backend:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - backend
      - postgresdb
    networks:
      - ionet

  backend:
    build:
      context: ./laravel-backend
      dockerfile: Dockerfile
    container_name: IO_backend
    volumes:
      - ./laravel-backend:/var/www/html
    ports:
      - "9001:9000"

  postgresdb:
    image: postgres:14-alpine
    container_name: IO_db
    env_file:
      - ./laravel-backend/.env
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_app
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - ionet

  frontend:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 5174:5173
    volumes:
      - ./vue-frontend:/app/vue-frontend
    depends_on:
      - backend
    networks:
      - ionet
